image: "ubuntu:20.04"

before_script:
- apt-get update -qq && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git curl wget sudo zip tzdata && \
  rm -rf /var/lib/apt/lists/* && \
  ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime && \
  dpkg-reconfigure --frontend noninteractive tzdata

install & test:
  script:
  - /bin/bash -c "./setup_home.sh"
  - /bin/bash -c "./run_tests.sh"